baseURL = "https://omerfarukalaca.com/"
title = "ğŸ‘¨ğŸ»â€ğŸ’»"
theme = "PaperMod"
defaultContentLanguage = "en"
languageCode = "en-us"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true

[params]
env = "production"
title = "ğŸ‘¨â€ğŸ’»"
description = "Software Engineer"
keywords = ["Blog", "Portfolio", "Software Engineer"]
author = "Ã–mer Faruk Alaca"
images = ["/img/profile.jpeg"]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = false
ShowShareButtons = false
ShowPostNavLinks = false
ShowBreadCrumbs = false
ShowCodeCopyButtons = true
ShowWordCount = false
ShowRssButtonInSectionTermList = false
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false
label.icon = "ğŸ‘¨â€ğŸ’»"
label.iconHeight = "35"

  [params.profileMode]
    enabled = true
    title = "Ã–mer Faruk Alaca"
    subtitle = "ğŸš€ Crafting scalable solutions [@Trendyol](https://www.linkedin.com/company/trendyolgroup) | Senior Software Engineer"
    imageUrl = "/img/profile.jpg"
    imageWidth = 160
    imageHeight = 160
    imageTitle = "Profile Photo"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/omerfarukalaca"
  title = "Check out my projects"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://linkedin.com/in/omerfarukalaca"
  title = "Connect with me"
